### ISSUE TITLE
既然可以记录被ban的评论，那可以记录正常的评论吗

### ISSUE THREAD

**Issue by efaun** [freedom-introvert/biliSendCommAntifraud#10]
比较苦恼B站不能看自己评论过的动态，有时候还得找半天，这个功能你可以支持吗，虽然不太符合这个模块的功能😂

**Comment by freedom-introvert** [comment]
可以，这个以后再说。我也觉得这个功能有必要加上去，并且提供以下功能：再检查评论状态，可检查是否被删除、invisible。

**Comment by UNTRIVAL** [comment]
能实现查询某用户的过往评论不？doge

**Comment by freedom-introvert** [comment]
我只能在你发送评论并调起应用检查的时候进行记录，获取你哔哩哔哩账号所有发布的评论做不到😂

**Comment by freedom-introvert** [comment]
已实现
