### ISSUE TITLE
在专栏发评论不会触发自动检测

### ISSUE THREAD

**Issue by Huaxidesu** [freedom-introvert/biliSendCommAntifraud#15]
哔哩哔哩版本：7.31.0
插件版本：3.0.0bata
这里分别测试了视频，动态，专栏，只有专栏无法触发自动检测
![Screenshot_2023-07-02-16-09-34-310_icu freedomIntrovert biliSendCommAntifraud](https://github.com/freedom-introvert/biliSendCommAntifraud/assets/45794248/73880487-feb2-4619-9fed-13b6c8027fe4)
![Screenshot_2023-07-02-16-09-49-641_tv danmaku bili](https://github.com/freedom-introvert/biliSendCommAntifraud/assets/45794248/d04c3a4e-f73e-4bd7-963d-fd15d077a82b)
![Screenshot_2023-07-02-16-09-13-593_icu freedomIntrovert biliSendCommAntifraud](https://github.com/freedom-introvert/biliSendCommAntifraud/assets/45794248/1f9963a3-4ccc-4c78-af9e-c76f10cc118a)

**Comment by freedom-introvert** [comment]
专栏是webwiew，也就是浏览器套壳实现的，这个我没辙啊

**Comment by Xx114514xX1819** [comment]
已经修复，可以关闭issue了
