### ISSUE TITLE
一个有局限的检测方法以及invisible状态的触发条件

### ISSUE THREAD

**Issue by mgmzdbh25365** [freedom-introvert/biliSendCommAntifraud#18]
检测方法
------------
当在动态下发表的评论被删除或shadowban，无论是否是游客还是登录状态,都无法跳转至评论(形如：https://t.bilibili.com/******************#reply************)。
此时在网页开发者工具(F12)的控制台可见`[comment] dom not find when jump`。由https://s1.hdslb.com/bfs/seed/jinkela/commentpc/comment.min.js 发出。
最后得到相关接口`GET api.bilibili.com/x/v2/reply/jump?jsonp=jsonp&rpid=************&oid=******************&type=17`
如果在接口返回数据中没有找到所请求的`rpid`，则评论已被删除或shadowban。

`invisible`触发条件
------------
当用户在up主的视频下发表了楼中楼评论，后续该用户被up主拉黑，则评论不会正常显示，被赋予`invisible=true`。
> 例如https://www.bilibili.com/video/BV1354y1o77h?comment_on=1&comment_root_id=114606873056&comment_secondary_id=115828683632 下的一条评论，内容为“`救命长得好像肖战。。`”；
在点开楼中楼详情前可看到`共3条回复, 点击查看`。
点开后却只显示1条回复，使用模块后会发现另外两条隐藏回复。
相关证据是https://b23.tv/av299860628

**Comment by freedom-introvert** [comment]
谢谢你的研究，给研究档案增加了一条😆
