### ISSUE TITLE
弹幕检测没移除干净

### ISSUE THREAD

**Issue by Xx114514xX1819** [freedom-introvert/biliSendCommAntifraud#25]
如图，在菜单中的发评后等待时长设置里还保留着弹幕发送后等待时间设置选项，可是弹幕检测已经被移除了，建议把这个设置也移除了
![Screenshot_2023-09-10-17-27-19-932_icu freedomIntrovert biliSendCommAntifraud](https://github.com/freedom-introvert/biliSendCommAntifraud/assets/114345474/44533c3a-e60b-412f-875c-2a29766d35a7)

**Comment by freedom-introvert** [comment]
😂😂😂，留作彩蛋吧，下个版本改成~~弹幕发送之后等待~~，其实源代码也没有移除干净，给会的大佬修改来用，他会更好的检查方式就让他来吧。
