### ISSUE TITLE
你这后台等待有问题啊

### ISSUE THREAD

**Issue by Xx114514xX1819** [freedom-introvert/biliSendCommAntifraud#28]
发送一条评论，点击后台等待，然后就没有然后了，通知栏屁都没有，重复了6次都一样
redmi k50u
miui14
android13
lsposed6990
bilibili7490 
不想提供log，因为懒得装lsp的debug版本

**Comment by freedom-introvert** [comment]
忘记申请通知权限了，淦🤡

**Comment by ZerOri** [comment]
> 淦

最近发现一个细节，b站后台应该是有账号标记系统，被标记过的账号相比普通账号评论动态会被严格限制，这也是为什么同样一条评论或关键字有的账号能发有的账号立马和谐的原因。账号标记标准有两种可能的情况：
1.过往评论触发系统风控多次被系统删评。
2.评论被人举报后人工删评手动标记。
基本上被标记的账号评论就算废了，但凡有一点关键词评论都会被系统秒删。比如我的账号已经连“诛九族”这种无伤大雅的词都发不出了。

**Comment by unx123475** [comment]
还有个问题，你这后台等待的，没收入历史评论中

**Comment by freedom-introvert** [comment]
抱歉各位，给大家留了那么多bug😂，这个周末给大家修好！因为我现在正忙YouTube发评反诈，被YouTube的变态（答辩）API搞吐了，每条评论的item下面都跟着一个emoji list，小学生水平的程序员都不带这么玩的😅！还他妈JSON API里套protobuf的base64，吐了。

**Comment by unx123475** [comment]
> 抱歉各位，给大家留了那么多bug😂，这个周末给大家修好！因为我现在正忙YouTube发评反诈，被YouTube的变态（答辩）API搞吐了，每条评论的item下面都跟着一个emoji list，小学生水平的程序员都不带这么玩的😅！还他妈JSON API里套protobuf的base64，吐了。

请不要着急！一步一步来就好了🤝

**Comment by ZerOri** [comment]
> 抱歉各位，给大家留了那么多bug😂，这个周末给大家修好！因为我现在正忙YouTube发评反诈，被YouTube的变态（答辩）API搞吐了，每条评论的item下面都跟着一个emoji list，小学生水平的程序员都不带这么玩的😅！还他妈JSON API里套protobuf的base64，吐了。

不会吧，油管也玩这套😅

**Comment by freedom-introvert** [comment]
> 不会吧，油管也玩这套😅

![IMG_20230908_081659](https://github.com/freedom-introvert/biliSendCommAntifraud/assets/127455583/96cd27fb-42d0-4d32-8a79-5a26baeb7899)
是的，看这个，这是某位群友的

**Comment by freedom-introvert** [comment]
还有问题吗？
