### ISSUE TITLE
用不明白

### ISSUE THREAD

**Issue by xzlosats111** [freedom-introvert/biliSendCommAntifraud#29]
自己对lspxp没多少了解，所以如果问比较傻逼的问题请包涵一下
安装完lsp模块，启用，获取cookie，在模块APP里面测试正常，到B站APP里面发评论，不知道哪部没搞对，就什么都没发生
miui13，B站是内置漫游的版本，有开应用分身，7.31.0

**Comment by freedom-introvert** [comment]
应用分身用不了任何模块吧

**Comment by xzlosats111** [comment]
> 应用分身用不了任何模块吧

今天试了一下确认是漫游版app的问题，之前偷懒用的是他们封好的lspatch便携版，用着用着bug越积累越多，现在受不了直接用原版客户端加lsposed注入，各种问题就都没了，你的这个模块也可以正常用了

**Comment by xzlosats111** [comment]
> 应用分身用不了任何模块吧

另外，应用分身也是可以应用lsp模块的，我正好B站有应用分身的需求，为了想办法共存在经历了一系列痛苦的改包名之类的折腾后，而且改包名用某些功能还会闪退，到最后我才突然发现lsp原生支持应用双开，那个安装到x space就是用来干这个的了
