### ISSUE TITLE
不要阻塞UI

### ISSUE THREAD

**Issue by wsy998** [freedom-introvert/biliSendCommAntifraud#3]
检测的时候不要阻塞UI，然后结果的话可以通过通知来给用户说明，正常显示不需要通知，其他情况通知一下

**Comment by freedom-introvert** [comment]
啊这，检查的时间也不长啊，也就5秒这样，要实现你的想法得改蛮多代码。
不过，反观墙外的YouTube也有类似阿瓦隆的东西，不是仅自己可见，而是一段时间后删评，这时间内评论别人可见的，这个时间要1分钟，之后回复评论就报错。如果说是YouTube这种检查时间特别长的话，那你的想法还是合理的。（当然我没做YT发评检查😂，这需要更多精力还要软路由）
你真的很需要这个功能吗？如果不是很需要，能不能容我偷个懒🤤

**Comment by XiaoMiku01** [comment]
检查时候起个单独的线程，用toast来通知也行

**Comment by freedom-introvert** [comment]
但是检查是startActivity到我的APP的透明activity上的，而不是直接把dialog注入哔哩哔哩，难改的是这个

**Comment by wsy998** [comment]
我只是建议，毕竟我大学也是学过安卓的，这样是稍微提升一下用户体验，就是有的时候我就发条评论，就向退出去了，本能的返回，然后发现需要等3s，虽然时间也不长

**Comment by CCA2878** [comment]
可以改toast通知啊，另外能否加一个隐藏桌面图标的选项

**Comment by freedom-introvert** [comment]
如果用toast通知，评论被ban了就不能做后续处理了😅

**Comment by wsy998** [comment]
我的建议还是用通知比较好，通知接自己的通知

**Comment by tlw00988** [comment]
> 如果用toast通知，评论被ban了就不能做后续处理了😅

那么可以用带有交互（就是和米窗的那个）的那样

**Comment by Reilkay** [comment]
或许可以后台检测，有异常的话再起这个activity

**Comment by Xx114514xX1819** [comment]
特别是发评论带图的时候要等十几秒真的很难受

**Comment by freedom-introvert** [comment]
我正在开发这个功能，是否是你想要的？
![IMG_20230910_180229](https://github.com/freedom-introvert/biliSendCommAntifraud/assets/127455583/ce2e755f-8647-4e30-896f-99748939d274)
![IMG_20230910_180248](https://github.com/freedom-introvert/biliSendCommAntifraud/assets/127455583/a776b36b-3cdb-456e-b5c2-8808049b053e)

**Comment by Xx114514xX1819** [comment]
最好是发完评论后直接默认在后台等待并且检测，如果没问题的话就直接不提示过了，有问题就弹窗询问下一步操作

**Comment by freedom-introvert** [comment]
4.4.0版本实现了通知栏进度
