### ISSUE TITLE
几点优化建议

### ISSUE THREAD

**Issue by XiaoMiku01** [freedom-introvert/biliSendCommAntifraud#4]
1. 检查时候单独线程,不阻塞主线程,可以尝试用 kt 重写，毕竟 kt 的协程挺好用的
2. 用 `GET api.bilibili.com/x/v2/reply/info` 这个api来检查评论是否存在，这个 api 只需要一个 rpid 参数就那拿到评论详情
3. cookie 无需手动填写，可以直接 hook B站接口拿请求头里面的 token

**Comment by XiaoMiku01** [comment]
作者不介意的话，我周末有时间可以来pr

**Comment by freedom-introvert** [comment]
请给个`api.bilibili.com/x/v2/reply/info`的完整请求示例，包含参数一起

**Comment by XiaoMiku01** [comment]
额，刚测了一下，这个接口关闭了

**Comment by freedom-introvert** [comment]
关于“可以直接 hook B站接口拿请求头里面的 token”，这个的话比较困难还不好使。哔哩哔哩APP发送评论用的是access_key鉴权，直接在from表单里，抓包到的reply/add请求里甚至都没有cookie，而检查评论状态用的reply/reply请求，用的是cookie鉴权，access_key没用的，会直接等于没登录！
如果你还是想按照你的想法实现，那你可以下载源码来修改，自己动手实现一下，如果完全可行，那么我就把你的代码合并进去😄

**Comment by freedom-introvert** [comment]
两天了，如果你没有做的话，那我就close这个issues了
