### ISSUE TITLE
LSPosed仓库无法识别到已安装此模块，LSP仓库里的仓库名是不是忘记有大写的了，导致无法自动检测更新

### ISSUE THREAD

**Issue by hzy132** [freedom-introvert/biliSendCommAntifraud#42]
如题，我是在lsp下载安装的模块，我确认模块页面存在发评反诈模块，并且重启过了，在仓库页面的发评反诈没有注明“已安装”，且明明我的模块不是最新版本，也没有提示我有可用更新。我看lsp仓库名称全为小写，apk包名却有几个首字母是大写的，可能是这样的原因没有匹配上。

**Comment by freedom-introvert** [comment]
很多用户好像都没有这个问题

**Comment by SpeedPartner** [comment]
+1,我也遇到了...
