### ISSUE TITLE
5.2.1安装包未签名，无法安装至手机

### ISSUE THREAD

**Issue by 2SHANINGITHUB** [freedom-introvert/biliSendCommAntifraud#46]
在[github releases](https://github.com/freedom-introvert/biliSendCommAntifraud/releases/tag/5.2.1)下载apk试图安装至手机时，提示安装包无效，安装包缺乏开发者证书，无法安装。

**Comment by freedom-introvert** [comment]
这是纪念版彩蛋🤪
去lsp仓库下载是带签名的
