### ISSUE TITLE
大佬有计划适配其他APP吗？

### ISSUE THREAD

**Issue by Andrea-lyz** [freedom-introvert/biliSendCommAntifraud#6]
比如贴吧微博，这模块简直深得我心！
爱了，赞美大佬！
![Screenshot_2023-05-26-17-58-45-55_149003a2d400f6adb210d7e357a3a646.jpg](https://github.com/freedom-introvert/biliSendCommAntifraud/assets/52863141/2f1566ba-beee-4ce8-94fe-47869925c412)

另外有点小建议，关于发评检测弹窗，比如说评论成功了，因为弹窗内容带有原评论，“评论成功”四个在最后，希望让这个状态提示更加显眼，比如成功就用绿色字体，失败就红色

**Comment by freedom-introvert** [comment]
贴吧冲塔冲多了，把号冲没了，但是贴吧删评好像都是会提示的吧。微博我根本没有玩过，而且那里是键政的主战场。很抱歉撒，这些应用我根本就没有适配的打算😂

**Comment by freedom-introvert** [comment]
我觉得原来的就行了吧，被ban时显示有状态icon，底部还有一排按钮，正常显示的时候这些都没有，应该很好辨认的吧？
回到适配其他应用的话题上，因为我几乎我只玩哔哩哔哩而已，那些应用的那些应用的控评逻辑都跟哔哩哔哩差的很远

**Comment by Andrea-lyz** [comment]
> 贴吧冲塔冲多了，把号冲没了，但是贴吧删评好像都是会提示的吧。微博我根本没有玩过，而且那里是键政的主战场。很抱歉撒，这些应用我根本就没有适配的打算😂

👌🏻👌🏻了解。。不过贴吧是删帖有提示，折叠评论没有，和b站一样特离谱。至于微博，评论折叠连自己都看不见，但反而折叠帖子不提示。这些APP的控评手段真的恶心坏了。
至于增强提示方面，我说的是这里，图片里的还好，一旦评论长起来，评论成功四个字就会在很后面了
![Screenshot_2023-05-27-13-00-22-54_0ab1adaa7e395dc88498f051c1b07b90.jpg](https://github.com/freedom-introvert/biliSendCommAntifraud/assets/52863141/4d608980-f735-4de9-9522-1ebd8131590a)
