### ISSUE TITLE
需求：弹幕反诈

### ISSUE THREAD

**Issue by li7355608** [freedom-introvert/biliSendCommAntifraud#71]
现在弹幕也会诈骗了，发弹幕现在也得反诈，日后能不能加入这个功能？

**Comment by freedom-introvert** [comment]
之前有但是删了，因为弹幕没了，很多时候并不是诈骗，而是因为屏幕空间有限，不给装载上去罢了

**Comment by li7355608** [comment]
并不是评论区弹幕，而是直播间那种实时弹幕，直播时出现过很多次明明弹幕发送成功，但是主播根本看不到的情况。应该是接入了同样的诈骗和谐系统
